### ISSUE TITLE
Schedule "segment per node" parameter is ignored

### ISSUE THREAD

**Issue by enricocavallin** [thelastpickle/cassandra-reaper#1030]
**Spotted on 2.2.1 (4be9bfc)** and also on 2.1.3

When creating a new **schedule** with "Segments per node" valorized, it is ignored and default 0 is persisted.

Creating a new **repair** run with "Segments per node" valorized works fine.

**Comment by averzicco** [comment]
I see this happening also on 2.2.2

**Comment by joelsdc** [comment]
Could this be a workaround?

1- Schedule a repair
2- stop reaper
3- update the "segment per node" value in the database directly
4- start reaper

**Comment by adejanovski** [comment]
I pushed a PR with the fix: #1041 

Any testing to verify that the fix works would be much appreciated.
I can push a docker image or build a deb/rpm package with the fix if that helps.

**Comment by adejanovski** [comment]
This bug was fixed in 2.2.3 which was just released.

**Comment by ashishbitm** [comment]
The bug is still there in 2.2.3 . will be happy to share the logs if needed for any developer's review
